### ISSUE TITLE
Utiliser un linter

### ISSUE THREAD

**Issue by kindlyfire** [UrLab/incubator#163]
Ce serait cool d'un jour ajouter un linter et de checker automatiquement sur Travis CI. 

Possibilités de linter: [yapf](https://github.com/google/yapf), [black](https://github.com/psf/black), [pylint](https://www.pylint.org/), [flake8](http://flake8.pycqa.org/en/latest/#) et pleins d'autres...

**Comment by C4ptainCrunch** [comment]
https://pythonspeed.com/articles/pylint/ btw

**Comment by fgrimau** [comment]
@C4ptainCrunch on peut ajouter facilement des tests flake8/pylint avec travis, une préférence ?
