### ISSUE TITLE
reverse VS caractères spéciaux

### ISSUE THREAD

**Issue by fgrimau** [UrLab/incubator#176]
Les caractres spéciaux dans les pseudo font crasher le les reverse d'url.

**Comment by aantuness** [comment]
On peut rajouter dans le regex : À-ÖØ-öø-ÿ comme ca on est complient a une vaste nombre de caracteres

**Comment by Dolgarr** [comment]
et á

**Comment by thibault-v** [comment]
MAIS C'EST DE LA DISCRIMINATION !!
(scrimination)

**Comment by fgrimau** [comment]
@thibault-v j'avoue tu m'avais manqué sur ce genre de choses
