### ISSUE TITLE
Ajout de commentaires sur les projets

### ISSUE THREAD

**Issue by Minigrim0** [UrLab/incubator#197]
Ajouter des commentaires sous les projets pour pouvoir discuter facilement de la réalisation des projets, faire des suggestions, ...

**Comment by Mixone-FinallyHere** [comment]
Pouvoir faire des commentaries sur les taches concretment est peut etre utile aussi?

**Comment by thibault-v** [comment]
> Pouvoir faire des commentaries sur les taches concretment est peut etre utile aussi?

Soon™ un jira à UrLaB ! :trollface: 
cc: @etnarek 


(Je troll mais en vrai, c'est une très bonne idée ;-))
