### ISSUE TITLE
Fabricant Mac

### ISSUE THREAD

**Issue by altf4arnold** [UrLab/incubator#210]
Plutôt qu'afficher des mac adresses altérées quand on a pas de hostname, on peut afficher le fabriquant de la carte réseau...

**Comment by C4ptainCrunch** [comment]
Il me semble qu'on avait réfléchi à ça à l'époque mais que justement on cache le début de la mac (qui contient le fabriquant) expressément. Il me semble que certains membres du HS avaient des cartes réseau dont le fabriquant était trop reconnaissable

**Comment by altf4arnold** [comment]
J'aurai tendance à dire que normalement, les mac des membres connus sont sensées être encodée sur un user. Du coup, le seul cas ou ça pourrait arriver, à priori, c'est si quelqu'un avec une machine particulièrement atypique se retrouve au HS avec le stealth mode coupé sans avoir encodé sa mac dans l'incubateur et vient suffisamment couramment que pour établir le lien entre sa machine et la personne...

Ça semble relativement peu commun selon moi mais ce n'est que mon avis

**Comment by thibault-v** [comment]
> les mac des membres connus sont sensées être encodée sur un user.
Je suis un membre connu ... ma mac n'est pas encodé sur un user. Cela invalide ta proposition, non ? xD

Je vais dans le sens de C4, si t'as pas envie d'être reconnu dans Pamela et que tu choisis donc volontairement de pas "jouer le jeu", il n'est pas "fair" que Pamela affiche la marque de ta machine qui peut être un facteur assez discriminant.

Le choix d'origine de prendre la partie aléatoire de la mac me semble toujours pertinent.

**Comment by altf4arnold** [comment]
Bon ben dans ce cas, je close
