### ISSUE TITLE
Absence dans le Hackeragenda

### ISSUE THREAD

**Issue by BamBalaam** [UrLab/incubator#22]
Avec le nouveau site et format des event, les event UrLab ne sont plus repris dans l'Hackeragenda.

**Comment by C4ptainCrunch** [comment]
Il faut juste que @Psycojoker déploie https://github.com/Psycojoker/hackeragenda/commit/03b5281245854bfb2d5f535a373ab7f72db4e7c6 et on est bons :)
(il parait qu'on peut l'oppresser sur IRC pour qu'il le fasse plus vite)

**Comment by C4ptainCrunch** [comment]
Il semblerait qu'il faille encore un peu oppresser  @Psycojoker :)

**Comment by BamBalaam** [comment]
Done.
