### ISSUE TITLE
Hasher les adresses mac

### ISSUE THREAD

**Issue by PierreGe** [UrLab/incubator#23]
Salut !

Pour éviter la close contractuelle suivante liant l'utilisateur à UrLab© : 

 """ En donnant votre adresse MAC©, vous acceptez l'enregistrement de l'association entre votre pseudonyme et l'adresse matérielle de votre ordinateur sur le serveur de UrLab©."""

Il pourrait être une idée de hasher (exemple sha1) les adresses mac.
C'est une tache assez simple en python.
`import hashlib`
`hash_object = hashlib.sha1(b'Hello World')`
`hex_dig = hash_object.hexdigest()`
`print(hex_dig)`

**Comment by C4ptainCrunch** [comment]
C'est pas con :) Mais ça ajoute un petit peu de complexité et surtout, ça empêche un utilisateur de savoir lesquelles de ses MAC sont déjà en db. Enfin bon, why not :)
