### ISSUE TITLE
Password change Admin backend not working

### ISSUE THREAD

**Issue by aantuness** [UrLab/incubator#252]
Error received: 
Utilisateur avec l’identifiant « xxx/password » n’existe pas. Peut-être a-t-il été supprimé ?

**Comment by altf4arnold** [comment]
On dirait que ça casse le système de récupération automatique de MDP aussi

**Comment by aantuness** [comment]
![image](https://user-images.githubusercontent.com/32838369/117205980-9517fc00-adf2-11eb-9c1d-c30aa1b19393.png)


This is not not working for more info
