### ISSUE TITLE
Ajouter une page pour les kits Ba1

### ISSUE THREAD

**Issue by Minigrim0** [UrLab/incubator#269]
Sur une URL du style `https://urlab.be/kits`. Plus simple que sur github pour les moins expérimentés et ca les fait venir un peu sur notre site :)

**Comment by C4ptainCrunch** [comment]
Btw, il existe un système de short link sur l'incubateur genre https://urlab.be/wsgit redirige sur https://github.com/UrLab/wsgit2017/wiki/aide-m%C3%A9moire

Vous pouvez en rajouter d'autres sur https://urlab.be/admin/redir/redirection/
(Ce qui permettrait peut-être de rediriger urlab.be/kits vers le wiki ou quelque chose du genre)

**Comment by Minigrim0** [comment]
En fait on pourrait faire ça mais il faudrait alors ajouter une arborescence sur le wiki pour pouvoir plus facilement linker les différents "chapitres"

**Comment by Mortinat** [comment]
Personnellement je pense ca reste trop "complique" pour les ba1 , il faut que ca soit le plus simple possible sinon ils auront la flemme

**Comment by C4ptainCrunch** [comment]
Y'a aussi les pages statiques ou on peut mettre ce qu'on veut en fait: 
https://urlab.be/kits/
https://urlab.be/admin/flatpages/flatpage/7/change/

**Comment by Minigrim0** [comment]
Je pense qu'on peut partir sur les pages statiques du coup, @Mortinat tu peux rouvrir l'issue si tu n'est pas d'accord
