### ISSUE TITLE
Wiki pages are truncated. 

### ISSUE THREAD

**Issue by BamBalaam** [UrLab/incubator#42]
The bottom part of the wiki pages are truncated by the footer. 

Example: 

![Example](http://i.imgur.com/LEL1xv3.png)

**Comment by C4ptainCrunch** [comment]
C'est connu, y'a une poule (foireuse) en cours pour résoudre ca

**Comment by BamBalaam** [comment]
Fixed by c5d2e3d929f592602076d68a928f2adcf29afdb1
