### ISSUE TITLE
Le logo a des bords tout moches.

### ISSUE THREAD

**Issue by BamBalaam** [UrLab/incubator#46]
C'est tout moche. Je veux bien faire un bord transparent "ce soir ou demain".

![C'est trop moche](http://i.imgur.com/Hm1HJ0G.png)

**Comment by C4ptainCrunch** [comment]
Oui

**Comment by titouanc** [comment]
Effectivement

**Comment by PierreGe** [comment]
@titouanc As-tu toujours la base utilisé pour l'effet de lumière dans les yeux?

**Comment by titouanc** [comment]
J'ai juste utilisé https://github.com/UrLab/incubator/blob/master/static/img/space-invaders.png et rajouté un effet "Supernova" (si je me souviens bien du nom) avec Gimp.

**Comment by BamBalaam** [comment]
![Mockup](http://i.imgur.com/o18i3WB.png)

Better?

**Comment by C4ptainCrunch** [comment]
:+1:

**Comment by PierreGe** [comment]
Nickel :+1:
