### ISSUE TITLE
La page "About" est introuvable

### ISSUE THREAD

**Issue by PierreGe** [UrLab/incubator#55]
<img width="1280" alt="screen shot 2016-01-13 at 4 36 37 pm" src="https://cloud.githubusercontent.com/assets/2781180/12298737/e175e04a-ba13-11e5-96ae-e911bb0ac05f.png">

**Comment by titouanc** [comment]
C'est lié à la façon dont django-flatpage sert les pages https://docs.djangoproject.com/en/1.9/ref/contrib/flatpages/#django.contrib.flatpages.middleware.FlatpageFallbackMiddleware

Pas encore lu la doc pour les moyens de fixer ça

**Comment by C4ptainCrunch** [comment]
Fixed by #56 (thx @etnarek )
