### ISSUE TITLE
Erreur 500 lorsque l'Incubator ne peut pas émettre les messages temps-réel vers un routeur crossbar

### ISSUE THREAD

**Issue by titouanc** [UrLab/incubator#59]
Lorsque le client crossbar ne peut pas se connecter au broker (*ex: table de routage incomplète*), ça raise une exception, qui résulte en une 500. Ca impacte toutes les actions qui sont envoyées à LechBot (création/modification d'un projet/event/wiki), et ça vient d'ici https://github.com/UrLab/incubator/blob/master/realtime/helpers.py#L7-L20.

Il faudrait idéalement mettre le code "dangereux" dans un `try ... except`, et envoyer l'erreur vers sentry tout en n'impactant pas la réponse à l'utilisateur. Je n'ai pas trouvé la config de sentry, @C4ptainCrunch tu pourrais y jeter un oeil ?

**Comment by C4ptainCrunch** [comment]
Ca semble fixé d'après https://github.com/UrLab/incubator/blob/master/realtime/helpers.py#L12-L31
@titouanc : tu confirmes ?
